// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI9dzGJdBGOSLSSaUj6JOF_Ga04pFmxl4',
    appId: '1:848561654074:web:5cf7c40c3332e1dc14e803',
    messagingSenderId: '848561654074',
    projectId: 'phoneauthentication-efabf',
    authDomain: 'phoneauthentication-efabf.firebaseapp.com',
    storageBucket: 'phoneauthentication-efabf.appspot.com',
    measurementId: 'G-71PHRH6S2K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUzY3jMoBA934E8FrioHGC6-KUQnjQx0E',
    appId: '1:848561654074:android:f2f98745709f901414e803',
    messagingSenderId: '848561654074',
    projectId: 'phoneauthentication-efabf',
    storageBucket: 'phoneauthentication-efabf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpi1ElMJ8ZAuJD27MattclM4kCNgDJA6M',
    appId: '1:848561654074:ios:ddd92e290750a41414e803',
    messagingSenderId: '848561654074',
    projectId: 'phoneauthentication-efabf',
    storageBucket: 'phoneauthentication-efabf.appspot.com',
    iosBundleId: 'com.example.astro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpi1ElMJ8ZAuJD27MattclM4kCNgDJA6M',
    appId: '1:848561654074:ios:ddd92e290750a41414e803',
    messagingSenderId: '848561654074',
    projectId: 'phoneauthentication-efabf',
    storageBucket: 'phoneauthentication-efabf.appspot.com',
    iosBundleId: 'com.example.astro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAI9dzGJdBGOSLSSaUj6JOF_Ga04pFmxl4',
    appId: '1:848561654074:web:4ef8fbc3299445d414e803',
    messagingSenderId: '848561654074',
    projectId: 'phoneauthentication-efabf',
    authDomain: 'phoneauthentication-efabf.firebaseapp.com',
    storageBucket: 'phoneauthentication-efabf.appspot.com',
    measurementId: 'G-HLV6E7LTPS',
  );
}
